### ISSUE TITLE
немного не так

### ISSUE THREAD

**Issue by w3lel** [Rebxxt/vue-token-launch#1]
https://github.com/Rebxxt/vue-token-launch/blob/b32d477679f262dc4872c50efdbd3d6656e669be/src/components/sections/EarlyAccess.vue#L95
тут должно быть скорее всего  transform: translate(0, 15%);
 ты возможно перепутал

**Comment by Rebxxt** [comment]
в css есть отдельный метод translate который позволяет избегать добавления лишних функций в transform. полезно когда надо выполнить только одну перестановку. Надо бы проверить как оно себя поведет если перед и после этой строки пихнуть rotate: <value>; либо transform: rotate(<value>);
