### ISSUE TITLE
синтаксис v-bind

### ISSUE THREAD

**Issue by w3lel** [Rebxxt/vue-token-launch#2]
https://github.com/Rebxxt/vue-token-launch/blob/b32d477679f262dc4872c50efdbd3d6656e669be/src/components/sections/FooterNavigation.vue#L7
ты используешь :key если уж начал копать в вуе, то используй v-bind

**Comment by Rebxxt** [comment]
v-bind используется в виде синтаксического сахара. какой подход лучше использовать на проекте - думаю должно определяться на старте, так как сильно зависит от его масштабов. Возможно на большом проекте было бы намного удобнее использовать полный синтаксис

**Comment by w3lel** [comment]
немного даже не сахар, v-bind юзается в вуе для связывание данных с атрибутом, а кей, юзается для кормления вуе в v-for, для эффективной отрисовки компонентов.

**Comment by Rebxxt** [comment]
Во второй версии vue рекомендуется использовать полный синтаксис если пишется не SPA приложение. В третьей версии (используется на проекте) разницы нет https://vuejs.org/api/built-in-directives.html#v-bind
