### ISSUE TITLE
3

### ISSUE THREAD

**Issue by w3lel** [Rebxxt/vue-token-launch#3]
https://github.com/Rebxxt/vue-token-launch/blob/b32d477679f262dc4872c50efdbd3d6656e669be/src/components/sections/TokenomicsInfo.vue#L87-L95
В вуе есть правило вечного this надо стараться уйти от стрелочных функций, попробуй заменить 
graphicClick(event, graphicType) {
  //console.log(graphicType, 'drag', event);
},
clipboard(value) {
  navigator.clipboard.writeText(value);
 // console.log('clipboard', value);
}

**Comment by Rebxxt** [comment]
Хорошее замечание, до сюда руки не дошли отрефакторить (компонент делался самым первым). Надо почитать разницу в использовании arrow expression и function expression во vue3. Будет исправлено
