### ISSUE TITLE
4

### ISSUE THREAD

**Issue by w3lel** [Rebxxt/vue-token-launch#4]
https://github.com/Rebxxt/vue-token-launch/blob/b32d477679f262dc4872c50efdbd3d6656e669be/src/components/sections/TokenomicsInfo.vue#L84
перемудрил сам себя, если у тебя токен это реактивный объект, то достаточно просто вернуть токен: bla bla.
ЭТО БАЗА, ЗАЧЕМ ref

**Comment by Rebxxt** [comment]
Сейчас готова только фронтовая часть, в настоящий момент бэк в разработке. Данная переменная будет заменяться при инициализации секции и туда планируется вставлять токен, поэтому удалять ref сейчас не требуется
